/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/food/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Food Image */
        post: operations["analyze_food_image_api_food_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friends/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Friend */
        post: operations["add_friend_api_friends_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friends/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove Friend */
        post: operations["remove_friend_api_friends_remove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friends/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Friends */
        get: operations["get_friends_api_friends__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/location/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Location */
        post: operations["resolve_location_api_location_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/photo/{photo_reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proxy Place Photo */
        get: operations["proxy_place_photo_api_places_photo__photo_reference__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences/blend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Blend Preferences */
        post: operations["blend_preferences_api_preferences_blend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/{user_id}/taste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Taste Profile */
        get: operations["get_taste_profile_api_profile__user_id__taste_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/restaurants/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Nearby Restaurants */
        post: operations["get_nearby_restaurants_api_restaurants_nearby_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/restaurants/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Restaurants */
        post: operations["search_restaurants_api_restaurants_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/restaurants/search-group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Group */
        post: operations["search_group_api_restaurants_search_group_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Review */
        post: operations["submit_review_api_reviews_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reviews */
        get: operations["get_reviews_api_reviews__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem Access */
        post: operations["redeem_access_api_v1_access_redeem_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Access */
        post: operations["validate_access_api_v1_access_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_api_v1_connections_get"];
        put?: never;
        /** Create Connection */
        post: operations["create_connection_api_v1_connections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections/{connected_profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Connection */
        delete: operations["delete_connection_api_v1_connections__connected_profile_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover */
        post: operations["discover_api_v1_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/food/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Food */
        post: operations["analyze_food_api_v1_food_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Location */
        post: operations["resolve_location_api_v1_locations_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_api_v1_me_delete"];
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Me */
        get: operations["export_me_api_v1_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_api_v1_plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_v1_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_v1_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Constraints */
        patch: operations["update_constraints_api_v1_plans__plan_id__constraints_patch"];
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize */
        post: operations["finalize_api_v1_plans__plan_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Plan */
        post: operations["join_plan_api_v1_plans__plan_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Recommendations */
        post: operations["generate_recommendations_api_v1_plans__plan_id__recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen */
        post: operations["reopen_api_v1_plans__plan_id__reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/share-token/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate Share Token */
        post: operations["rotate_share_token_api_v1_plans__plan_id__share_token_rotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Vote */
        put: operations["vote_api_v1_plans__plan_id__vote_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_api_v1_reviews_get"];
        put?: never;
        /** Create Review */
        post: operations["create_review_api_v1_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taste-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Taste Profile */
        get: operations["taste_profile_api_v1_taste_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taste-profile/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Taste */
        post: operations["regenerate_taste_api_v1_taste_profile_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Live */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BlendRequest */
        BlendRequest: {
            /** User Ids */
            user_ids: string[];
        };
        /** Body_analyze_food_api_v1_food_analyze_post */
        Body_analyze_food_api_v1_food_analyze_post: {
            /** Image */
            image: string;
        };
        /** Body_analyze_food_image_api_food_analyze_post */
        Body_analyze_food_image_api_food_analyze_post: {
            /** Image */
            image: string;
        };
        /** CandidateOut */
        CandidateOut: {
            /** Id */
            id: string;
            /** Match Score */
            match_score: number;
            place: components["schemas"]["PlaceOut"];
            /** Rank */
            rank: number;
            /** Reasoning */
            reasoning: string;
            /**
             * Vote Score
             * @default 0
             */
            vote_score: number;
        };
        /** ConnectionIn */
        ConnectionIn: {
            /** Profile Id */
            profile_id: string;
        };
        /** ConnectionOut */
        ConnectionOut: {
            /** Display Name */
            display_name: string;
            /** Profile Id */
            profile_id: string;
            /** Taste Profile */
            taste_profile: string | null;
        };
        /** ConstraintsIn */
        ConstraintsIn: {
            /** Cuisines */
            cuisines?: string[];
            /** Dietary Notes */
            dietary_notes?: string[];
            /** Max Price Level */
            max_price_level?: number | null;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** DeleteAccountOut */
        DeleteAccountOut: {
            /** Deleted */
            deleted: boolean;
        };
        /** DiscoverIn */
        DiscoverIn: {
            /** Latitude */
            latitude: number;
            /**
             * Limit
             * @default 20
             */
            limit: number;
            /** Longitude */
            longitude: number;
            /**
             * Query
             * @default
             */
            query: string;
        };
        /** Envelope[ConnectionOut] */
        Envelope_ConnectionOut_: {
            data: components["schemas"]["ConnectionOut"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[DeleteAccountOut] */
        Envelope_DeleteAccountOut_: {
            data: components["schemas"]["DeleteAccountOut"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[FoodAnalysisOut] */
        Envelope_FoodAnalysisOut_: {
            data: components["schemas"]["FoodAnalysisOut"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[InviteValidation] */
        Envelope_InviteValidation_: {
            data: components["schemas"]["InviteValidation"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[LocationOut] */
        Envelope_LocationOut_: {
            data: components["schemas"]["LocationOut"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[PlanCreated] */
        Envelope_PlanCreated_: {
            data: components["schemas"]["PlanCreated"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[PlanOut] */
        Envelope_PlanOut_: {
            data: components["schemas"]["PlanOut"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[ProfileOut] */
        Envelope_ProfileOut_: {
            data: components["schemas"]["ProfileOut"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[ReviewOut] */
        Envelope_ReviewOut_: {
            data: components["schemas"]["ReviewOut"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[ShareTokenOut] */
        Envelope_ShareTokenOut_: {
            data: components["schemas"]["ShareTokenOut"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[TasteProfileOut] */
        Envelope_TasteProfileOut_: {
            data: components["schemas"]["TasteProfileOut"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[list[ConnectionOut]] */
        Envelope_list_ConnectionOut__: {
            /** Data */
            data: components["schemas"]["ConnectionOut"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[list[PlaceOut]] */
        Envelope_list_PlaceOut__: {
            /** Data */
            data: components["schemas"]["PlaceOut"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[list[PlanOut]] */
        Envelope_list_PlanOut__: {
            /** Data */
            data: components["schemas"]["PlanOut"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Envelope[list[ReviewOut]] */
        Envelope_list_ReviewOut__: {
            /** Data */
            data: components["schemas"]["ReviewOut"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** FinalizeIn */
        FinalizeIn: {
            /** Candidate Id */
            candidate_id?: string | null;
        };
        /** FoodAnalysisOut */
        FoodAnalysisOut: {
            /** Cuisine */
            cuisine: string;
            /** Description */
            description: string;
            /** Dish */
            dish: string;
            /** Flavor Tags */
            flavor_tags: string[];
        };
        /** FriendAction */
        FriendAction: {
            /** Friend Id */
            friend_id: string;
            /** User Id */
            user_id: string;
        };
        /** GroupSearchRequest */
        GroupSearchRequest: {
            /** Latitude */
            latitude: number;
            /** Location Label */
            location_label: string;
            /** Longitude */
            longitude: number;
            /** Query */
            query: string;
            /**
             * Radius Meters
             * @default 2000
             */
            radius_meters: number;
            /** User Ids */
            user_ids: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InviteRedeemIn */
        InviteRedeemIn: {
            /** Display Name */
            display_name: string;
            /** Redemption Token */
            redemption_token: string;
        };
        /** InviteValidateIn */
        InviteValidateIn: {
            /** Code */
            code: string;
            /** Email */
            email?: string | null;
        };
        /** InviteValidation */
        InviteValidation: {
            /**
             * Expires In Seconds
             * @default 1200
             */
            expires_in_seconds: number;
            /** Redemption Token */
            redemption_token: string;
        };
        /** LocationIn */
        LocationIn: {
            /** Query */
            query: string;
        };
        /** LocationOut */
        LocationOut: {
            /** Label */
            label: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** LocationResolveRequest */
        LocationResolveRequest: {
            /** Query */
            query: string;
        };
        /** NearbyRequest */
        NearbyRequest: {
            /** Latitude */
            latitude: number;
            /**
             * Limit
             * @default 20
             */
            limit: number;
            /** Longitude */
            longitude: number;
            /**
             * Radius Meters
             * @default 2000
             */
            radius_meters: number;
        };
        /** ParticipantOut */
        ParticipantOut: {
            /** Constraints */
            constraints: {
                [key: string]: unknown;
            };
            /** Display Name */
            display_name: string;
            /** Is Organizer */
            is_organizer: boolean;
            /** Profile Id */
            profile_id: string;
        };
        /** PlaceOut */
        PlaceOut: {
            /** Address */
            address: string;
            /** Cuisine */
            cuisine: string;
            /**
             * Data Provider
             * @enum {string}
             */
            data_provider: "fixture" | "google_maps";
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Place Id */
            place_id: string;
            /** Price Level */
            price_level: number;
            /** Rating */
            rating: number;
        };
        /** PlanCreateIn */
        PlanCreateIn: {
            /** Latitude */
            latitude: number;
            /** Location Label */
            location_label: string;
            /** Longitude */
            longitude: number;
            /** Title */
            title: string;
        };
        /** PlanCreated */
        PlanCreated: {
            plan: components["schemas"]["PlanOut"];
            /** Share Token */
            share_token: string;
        };
        /** PlanJoinIn */
        PlanJoinIn: {
            /** Share Token */
            share_token: string;
        };
        /** PlanOut */
        PlanOut: {
            /** Candidates */
            candidates: components["schemas"]["CandidateOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finalized Candidate Id */
            finalized_candidate_id: string | null;
            /** Id */
            id: string;
            /** Latitude */
            latitude: number;
            /** Location Label */
            location_label: string;
            /** Longitude */
            longitude: number;
            /** My Vote */
            my_vote: string[] | null;
            /** Organizer Id */
            organizer_id: string;
            /** Participants */
            participants: components["schemas"]["ParticipantOut"][];
            /**
             * Status
             * @enum {string}
             */
            status: "collecting" | "voting" | "finalized";
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Viewer Is Organizer */
            viewer_is_organizer: boolean;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
            /** Share Taste */
            share_taste: boolean;
            /** Taste Profile */
            taste_profile: string;
        };
        /** ProfilePatch */
        ProfilePatch: {
            /** Display Name */
            display_name?: string | null;
            /** Share Taste */
            share_taste?: boolean | null;
        };
        /** RecommendationIn */
        RecommendationIn: {
            /** Query */
            query: string;
        };
        /** ReviewIn */
        ReviewIn: {
            /** Cuisine */
            cuisine?: string | null;
            /** Dish */
            dish?: string | null;
            /** Rating */
            rating: number;
            /** Restaurant Name */
            restaurant_name: string;
            /** Review Text */
            review_text: string;
        };
        /** ReviewOut */
        ReviewOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cuisine */
            cuisine?: string | null;
            /** Dish */
            dish?: string | null;
            /** Id */
            id: string;
            /** Rating */
            rating: number;
            /** Restaurant Name */
            restaurant_name: string;
            /** Review Text */
            review_text: string;
        };
        /** ReviewSubmitRequest */
        ReviewSubmitRequest: {
            /** Cuisine */
            cuisine?: string | null;
            /** Dish */
            dish?: string | null;
            /** Rating */
            rating: number;
            /** Restaurant Name */
            restaurant_name: string;
            /** Review Text */
            review_text: string;
            /** User Id */
            user_id: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Latitude */
            latitude: number;
            /** Location Label */
            location_label: string;
            /** Longitude */
            longitude: number;
            /** Query */
            query: string;
            /**
             * Radius Meters
             * @default 2000
             */
            radius_meters: number;
            /** User Id */
            user_id: string;
        };
        /** ShareTokenOut */
        ShareTokenOut: {
            /** Share Token */
            share_token: string;
        };
        /** TasteProfileOut */
        TasteProfileOut: {
            /** Preferences Text */
            preferences_text: string;
            /** Share Taste */
            share_taste: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VoteIn */
        VoteIn: {
            /** Ranking */
            ranking: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    analyze_food_image_api_food_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_food_image_api_food_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_friend_api_friends_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FriendAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_friend_api_friends_remove_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FriendAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_friends_api_friends__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_location_api_location_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proxy_place_photo_api_places_photo__photo_reference__get: {
        parameters: {
            query?: {
                maxwidth?: number;
            };
            header?: never;
            path: {
                photo_reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    blend_preferences_api_preferences_blend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_taste_profile_api_profile__user_id__taste_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_nearby_restaurants_api_restaurants_nearby_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NearbyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_restaurants_api_restaurants_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_group_api_restaurants_search_group_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_review_api_reviews_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reviews_api_reviews__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_user_api_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redeem_access_api_v1_access_redeem_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteRedeemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProfileOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_access_api_v1_access_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteValidateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_InviteValidation_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connections_api_v1_connections_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_ConnectionOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_connection_api_v1_connections_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ConnectionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_connection_api_v1_connections__connected_profile_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path: {
                connected_profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DeleteAccountOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_api_v1_discover_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_PlaceOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_food_api_v1_food_analyze_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_food_api_v1_food_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_FoodAnalysisOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_location_api_v1_locations_resolve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_LocationOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProfileOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_me_api_v1_me_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DeleteAccountOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProfileOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_me_api_v1_me_export_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_v1_plans_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_PlanOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_v1_plans_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlanCreated_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_v1_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlanOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_constraints_api_v1_plans__plan_id__constraints_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConstraintsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlanOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_api_v1_plans__plan_id__finalize_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalizeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlanOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_plan_api_v1_plans__plan_id__join_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanJoinIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlanOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_recommendations_api_v1_plans__plan_id__recommendations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlanOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reopen_api_v1_plans__plan_id__reopen_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlanOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_share_token_api_v1_plans__plan_id__share_token_rotate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ShareTokenOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vote_api_v1_plans__plan_id__vote_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlanOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_api_v1_reviews_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_ReviewOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_api_v1_reviews_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ReviewOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    taste_profile_api_v1_taste_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TasteProfileOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_taste_api_v1_taste_profile_regenerate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-demo-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TasteProfileOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
